[참고1]('https://lsjsj92.tistory.com/569?category=853217') [참고2]('https://www.kaggle.com/code/rajmehra03/cf-based-recsys-by-low-rank-matrix-factorization')

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import TruncatedSVD

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,roc_curve,roc_auc_score
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

# 데이터탐색

In [2]:
ratings = pd.read_csv('./dataset/movielens100k/ratings.csv')
ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [3]:
ratings.describe()

              userId        movieId         rating     timestamp
count  100004.000000  100004.000000  100004.000000  1.000040e+05
mean      347.011310   12548.664363       3.543608  1.129639e+09
std       195.163838   26369.198969       1.058064  1.916858e+08
min         1.000000       1.000000       0.500000  7.896520e+08
25%       182.000000    1028.000000       3.000000  9.658478e+08
50%       367.000000    2406.500000       4.000000  1.110422e+09
75%       520.000000    5418.000000       4.000000  1.296192e+09
max       671.000000  163949.000000       5.000000  1.476641e+09

In [4]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100004 entries, 0 to 100003
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100004 non-null  int64
 1   movieId    100004 non-null  int64
 2   rating     100004 non-null  float64
 3   timestamp  100004 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [5]:
movie_df = pd.read_csv('./dataset/movielens100k/movies.csv')
movie_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [6]:
ratings = pd.merge(ratings, movie_df, on = 'movieId')
ratings

,userId,movieId,rating,timestamp,title,genres
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama
1,7,31,3.0,851868750,Dangerous Minds (1995),Drama
2,31,31,4.0,1273541953,Dangerous Minds (1995),Drama
3,32,31,4.0,834828440,Dangerous Minds (1995),Drama
4,36,31,3.0,847057202,Dangerous Minds (1995),Drama
...,...,...,...,...,...,...
99999,664,64997,2.5,1343761859,War of the Worlds (2005),Action|Sci-Fi
100000,664,72380,3.5,1344435977,"Box, The (2009)",Drama|Horror|Mystery|Sci-Fi|Thriller
100001,665,129,3.0,995232528,Pie in the Sky (1996),Comedy|Romance
100002,665,4736,1.0,1010197684,Summer Catch (2001),Comedy|Drama|Romance
100003,668,6425,1.0,993613478,"6th Man, The (Sixth Man, The) (1997)",Comedy

In [8]:
ratings["userId"].unique()[:10]

array([  1,   7,  31,  32,  36,  39,  73,  88,  96, 110], dtype=int64)

In [6]:
len(ratings["userId"].unique())

671

In [9]:
len(ratings["movieId"].unique())

9066

671명의 고객, 9066개의 영화 평가로 600만개 이상의 데이터 중 10만개 추출하였으므로 1.6%의 데이터에 불과함. 모델선택시 고려 필요

# 데이터변환

In [46]:
# 범주형 변환

ratings.userId = ratings.userId.astype('category').cat.codes.values
ratings.movieId = ratings.movieId.astype('category').cat.codes.values
# ratings['userId'].value_counts(ascending=True)
# ratings['movieId'].unique()                  

# # utility metrics 생성
# index = list(ratings['userId'].unique())
# index = sorted(index)
# columns = list(ratings['movieId'].unique())
# columns = sorted(columns)

item_mtx= pd.pivot_table(data=ratings, values = 'rating', columns='userId',
                         index='title')
item_mtx = util_df.fillna(0)
item_mtx

userId,0,1,2,3,4,5,6,7,8,9,...,661,662,663,664,665,666,667,668,669,670
title,,,,,,,,,,,,,,,,,,,,,
"""Great Performances"" Cats (1998)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
$9.99 (2008),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Neath the Arizona Skies (1934),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Round Midnight (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
xXx (2002),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
xXx: State of the Union (2005),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
¡Three Amigos! (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
À nous la liberté (Freedom for Us) (1931),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
İtirazım Var (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 아이템 기반 협업필터링 추천
고객 평점이 유사한 영화 추천하기 위해, [코사인 유사도](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.cosine_similarity.html) 활용

In [49]:
item_based= cosine_similarity(util_df)
item_cf = pd.DataFrame(data = item_based, index= item_mtx.index , columns= item_mtx.index)
item_cf

title,"""Great Performances"" Cats (1998)",$9.99 (2008),'Hellboy': The Seeds of Creation (2004),'Neath the Arizona Skies (1934),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),...,Zulu (1964),Zulu (2013),[REC] (2007),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931),İtirazım Var (2014)
title,,,,,,,,,,,,,,,,,,,,,
"""Great Performances"" Cats (1998)",1.000000,0.000000,0.0,0.164399,0.020391,0.0,0.014046,0.000000,0.000000,0.003166,...,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0000
$9.99 (2008),0.000000,1.000000,0.0,0.000000,0.000000,0.0,0.000000,0.079474,0.000000,0.156330,...,0.000000,0.000000,0.0,0.000000,0.0,0.013899,0.000000,0.058218,0.0,0.0000
'Hellboy': The Seeds of Creation (2004),0.000000,0.000000,1.0,0.000000,0.000000,1.0,0.000000,0.217357,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0000
'Neath the Arizona Skies (1934),0.164399,0.000000,0.0,1.000000,0.124035,0.0,0.085436,0.000000,0.000000,0.019259,...,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0000
'Round Midnight (1986),0.020391,0.000000,0.0,0.124035,1.000000,0.0,0.010597,0.143786,0.000000,0.136163,...,0.000000,0.000000,0.0,0.121567,0.0,0.000000,0.000000,0.000000,0.0,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
xXx (2002),0.000000,0.013899,0.0,0.000000,0.000000,0.0,0.000000,0.123940,0.000000,0.144961,...,0.161281,0.076029,0.0,0.017465,0.0,1.000000,0.152057,0.140222,0.0,0.2661
xXx: State of the Union (2005),0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.134815,...,0.000000,0.000000,0.0,0.000000,0.0,0.152057,1.000000,0.000000,0.0,0.0000
¡Three Amigos! (1986),0.000000,0.058218,0.0,0.000000,0.000000,0.0,0.081620,0.331663,0.214498,0.064908,...,0.112588,0.159223,0.0,0.166622,0.0,0.140222,0.000000,1.000000,0.0,0.0000
À nous la liberté (Freedom for Us) (1931),0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,1.0,0.0000
İtirazım Var (2014),0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.134815,...,0.000000,0.000000,0.0,0.000000,0.0,0.266100,0.000000,0.000000,0.0,1.0000

In [52]:
# 영화 호출 함수
def movie_based_cf(title):
    return item_cf[title].sort_values(ascending=False)[:5]

# 테스트
movie_based_cf("$9.99 (2008)")

title
$9.99 (2008)                                                 1.000000
Kirikou and the Sorceress (Kirikou et la sorcière) (1998)    0.658145
Life is a Miracle (Zivot je cudo) (2004)                     0.658145
Wind Will Carry Us, The (Bad ma ra khahad bord) (1999)       0.658145
Head-On (Gegen die Wand) (2004)                              0.658145
Name: $9.99 (2008), dtype: float64

## 행렬분해 기반 협업필터링 추천
특정영화와 비슷한 영화를 추천해주기 위해 svd 활용
* [Singular Value Decomposition](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html)

In [58]:
user_mtx = pd.pivot_table(data=ratings, values = 'rating', columns='title',index='userId')
user_mtx = user_mtx.fillna(0)
user_mtx

title,"""Great Performances"" Cats (1998)",$9.99 (2008),'Hellboy': The Seeds of Creation (2004),'Neath the Arizona Skies (1934),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),...,Zulu (1964),Zulu (2013),[REC] (2007),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931),İtirazım Var (2014)
userId,,,,,,,,,,,,,,,,,,,,,
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
668,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
669,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
670,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [60]:
item_mtx.shape

(9064, 671)

In [63]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=12) # 9062개의 영화를 12개의 요소값으로 분류
svd_mtx = svd.fit_transform(item_mtx)
svd_mtx.shape

(9064, 12)

In [64]:
# 데이터 간 피어슨상관계수
corr = np.corrcoef(svd_mtx)
corr.shape

# 이 상관계수를 활용하여 '특정영화'와 상관계수 높은 영화를 뽑아주도록~

(9064, 9064)

In [78]:
titles = user_mtx.columns
title_list = list(titles)

idx = title_list.index("'Round Midnight (1986)")
corr_movie = corr[idx]

In [94]:
corr_movie.max(),corr_movie.min(), np.quantile(corr_movie,0.9)
titles[corr_movie>np.quantile(corr_movie,0.9)][:5]

Index([''Round Midnight (1986)',
       '20 Feet from Stardom (Twenty Feet from Stardom) (2013)',
       '200 Motels (1971)', '21 Up (1977)', '24: Redemption (2008)',
       '28 Up (1985)', '3 Women (Three Women) (1977)',
       '3 Worlds of Gulliver, The (1960)', '35 Up (1991)', '42 (2013)',
       ...
       'Wuthering Heights (1939)', 'X: The Man with the X-Ray Eyes (1963)',
       'Xiu Xiu: The Sent-Down Girl (Tian yu) (1998)',
       'Yankee Doodle Dandy (1942)', 'Year of the Horse (1997)',
       'Yentl (1983)', 'Your Sister's Sister (2011)',
       'Yours, Mine and Ours (1968)', 'Z (1969)', 'Zelig (1983)'],
      dtype='object', name='title', length=907)

In [133]:
titles = user_mtx.columns
title_list = list(titles)

def simular_movies(movie) :
    idx = title_list.index(movie)
    global corr, titles
    corr_dix = corr[idx]
    return list(titles[corr_movie>np.quantile(corr_movie,0.996)]) # 0.4% * 9064 

simular_movies("$9.99 (2008)")

["'Round Midnight (1986)",
 '45 Years (2015)',
 'Alice in the Cities (Alice in den Stadten) (1974)',
 'Apprenticeship of Duddy Kravitz, The (1974)',
 "Charlie's Country (2013)",
 'Comfort and Joy (1984)',
 'Festival Express (2003)',
 'Finding Vivian Maier (2013)',
 'Going Places (Valseuses, Les) (1974)',
 'Grey Gardens (2009)',
 'Groove Tube, The (1974)',
 'Hard Way, The (1943)',
 'Killing of a Chinese Bookie, The (1976)',
 'Last Wave, The (1977)',
 'Littlest Rebel, The (1935)',
 'Mondo Hollywood (1967)',
 'On Dangerous Ground (1952)',
 'Passenger, The (Professione: reporter) (1975)',
 "Ryan's Daughter (1970)",
 'Star Is Born, A (1954)',
 'State of Things, The (Stand der Dinge, Der) (1982)',
 'Take This Waltz (2011)',
 'The Lovers and the Despot',
 'The War at Home (1979)',
 'The Wild One (1953)',
 'They Live by Night (1949)',
 'Thousand Clowns, A (1965)',
 'What Happened, Miss Simone? (2015)']

In [134]:
len(simular_movies("$9.99 (2008)"))

28

유저,무비에 대해 인덱스 변수로 변환

In [15]:
users = ratings.userId.unique()
movies = ratings.movieId.unique()

userid2idx = {o:i for i,o in enumerate(users)}
movieid2idx = {o:i for i,o in enumerate(movies)}

useridx2id = {i:o for i,o in enumerate(users)}
movieidx2id = {i:o for i,o in enumerate(movies)}

ratings['userId'] = ratings['userId'].apply(lambda x: userid2idx[x])
ratings['movieId'] = ratings['movieId'].apply(lambda x: movieid2idx[x])

In [21]:
ratings

        userId  movieId  rating   timestamp
0            0       30     2.5  1260759144
1            0      833     3.0  1260759179
2            0      859     3.0  1260759182
3            0      906     2.0  1260759185
4            0      931     4.0  1260759205
...        ...      ...     ...         ...
99999      670     4545     2.5  1065579370
100000     670     4546     4.0  1065149201
100001     670     4597     4.0  1070940363
100002     670     4610     2.5  1070979663
100003     670     4696     3.5  1074784724

[100004 rows x 4 columns]