In [2]:
pwd
# pip install edgar
# https://pypi.org/project/python-edgar/

'C:\\study\\Python'

In [127]:
import edgar
import pandas as pd

# edgar리스트 다운로드
edgar.download_index('C:/study/Python/Stock/Edgar', 2018,skip_all_present_except_last=False)

# selectedcompany = 'Facebook'
selectedcompany = 'AT&T INC.'

selectedreport = '10-Q'

csv = pd.read_csv('C:/study/Python/Stock/Edgar/2020-QTR4.tsv', sep='\t',  lineterminator='\n', names=None) 

csv.columns.values[0] = 'Item'

companyreport = csv[(csv['Item'].str.contains(selectedcompany)) & (csv['Item'].str.contains(selectedreport))]

Filing = companyreport['Item'].str.split('|')
Filing = Filing.to_list()

for item in Filing[0]:   
    if 'html' in item:
        report = repr(item).split('\\')[0][1:]
url = 'https://www.sec.gov/Archives/' + report

document_list = pd.read_html(url)
document_index = document_list[0]
document_index = document_index.dropna()

document_name = document_index[document_index['Description'].str.contains(selectedreport)]
document_name = document_name['Document'].str.split(' ')
document_name = document_name[0][0]

report_formatted = report.replace('-','').replace('index.html','')
url = 'https://www.sec.gov/Archives/' + report_formatted + '/' + document_name

df = pd.read_html(url)

for item in df:
    print(item)
#     BS = (item[0].str.contains('Retained') | item[0].str.contains('Total Assets'))
#     if BS.any():
#         Balance_Sheet = item

# Balance_Sheet

# Balance_Sheet = Balance_Sheet.iloc[2:,[0,2,6]]

# header = Balance_Sheet.iloc[0]
# Balance_Sheet = Balance_Sheet[1:]

# Balance_Sheet.columns = header


# Balance_Sheet.columns.values[0] = 'Item'
# Balance_Sheet = Balance_Sheet[Balance_Sheet['Item'].notna()]

# Balance_Sheet[Balance_Sheet.columns[1:]] = Balance_Sheet[Balance_Sheet.columns[1:]].astype(str)
# Balance_Sheet[Balance_Sheet.columns[1]] = Balance_Sheet[Balance_Sheet.columns[1]].map(lambda x: x.replace('(','-'))
# Balance_Sheet[Balance_Sheet.columns[2]] = Balance_Sheet[Balance_Sheet.columns[2]].map(lambda x: x.replace('(','-'))


# Balance_Sheet[Balance_Sheet.columns[1]] = Balance_Sheet[Balance_Sheet.columns[1]].map(lambda x: x.replace(',',''))
# Balance_Sheet[Balance_Sheet.columns[2]] = Balance_Sheet[Balance_Sheet.columns[2]].map(lambda x: x.replace(',',''))

# Balance_Sheet[Balance_Sheet.columns[1]] = Balance_Sheet[Balance_Sheet.columns[1]].map(lambda x: x.replace('—','0'))
# Balance_Sheet[Balance_Sheet.columns[2]] = Balance_Sheet[Balance_Sheet.columns[2]].map(lambda x: x.replace('—','0'))



# Balance_Sheet[Balance_Sheet.columns[1:]] = Balance_Sheet[Balance_Sheet.columns[1:]].astype(float)

# Balance_Sheet

            0           1           2  \
0         NaN         NaN         NaN
1  (Mark One)  (Mark One)  (Mark One)
2           ☒           ☒           ☒

                                                   3  \
0                                                NaN
1                                         (Mark One)
2  QUARTERLY REPORT PURSUANT TO SECTION 13 OR 15(...

                                                   4  \
0                                                NaN
1                                         (Mark One)
2  QUARTERLY REPORT PURSUANT TO SECTION 13 OR 15(...

                                                   5   6   7   8
0                                                NaN NaN NaN NaN
1                                         (Mark One) NaN NaN NaN
2  QUARTERLY REPORT PURSUANT TO SECTION 13 OR 15(... NaN NaN NaN
     0    1    2                                                  3  \
0  NaN  NaN  NaN                                                NaN
1    ☐    ☐    ☐  TRANSITION REPORT PURSUANT TO SECTION 13 OR 15...

                                                   4  \
0                                                NaN
1  TRANSITION REPORT PURSUANT TO SECTION 13 OR 15...

                                                   5   6   7   8
0                                                NaN NaN NaN NaN
1  TRANSITION REPORT PURSUANT TO SECTION 13 OR 15... NaN NaN NaN
                                                    0  \
0                                                 NaN
1                                                 NaN
2                                 Title of each class
3           Common Shares (Par Value $1.00 Per Share)
4   Depositary Shares, each representing a 1/1000t...
5   Depositary Shares, each representing a 1/1000t...
6   AT&T Inc. 1.875% Global Notes due December 4, ...
7   AT&T Inc. 2.650% Global Notes due December 17,...
8      AT&T Inc. 1.450% Global Notes due June 1, 2022
9    AT&T Inc. 2.500% Global Notes due March 15, 2023
10     AT&T Inc. 2.750% Global Notes due May 19, 2023
11  AT&T Inc. Floating Rate Global Notes due Septe...
12  AT&T Inc. 1.050% Global Notes due September 5,...
13  AT&T Inc. 1.300% Global Notes due September 5,...
14  AT&T Inc. 1.950% Global Notes due September 15...
15   AT&T Inc. 2.400% Global Notes due March 15, 2024
16  AT&T Inc. 3.500% Global Notes due December 17,...
17    AT&T Inc. 0.250% Global Notes due March 4, 2026
18  AT&T Inc. 1.800% Global Notes due September 5,...

                                                    1  \
0                                                 NaN
1                                                 NaN
2                                 Title of each class
3           Common Shares (Par Value $1.00 Per Share)
4   Depositary Shares, each representing a 1/1000t...
5   Depositary Shares, each representing a 1/1000t...
6   AT&T Inc. 1.875% Global Notes due December 4, ...
7   AT&T Inc. 2.650% Global Notes due December 17,...
8      AT&T Inc. 1.450% Global Notes due June 1, 2022
9    AT&T Inc. 2.500% Global Notes due March 15, 2023
10     AT&T Inc. 2.750% Global Notes due May 19, 2023
11  AT&T Inc. Floating Rate Global Notes due Septe...
12  AT&T Inc. 1.050% Global Notes due September 5,...
13  AT&T Inc. 1.300% Global Notes due September 5,...
14  AT&T Inc. 1.950% Global Notes due September 15...
15   AT&T Inc. 2.400% Global Notes due March 15, 2024
16  AT&T Inc. 3.500% Global Notes due December 17,...
17    AT&T Inc. 0.250% Global Notes due March 4, 2026
18  AT&T Inc. 1.800% Global Notes due September 5,...

                                                    2                  3  \
0                                                 NaN                NaN
1                                                 NaN                NaN
2                                 Title of each class  Trading Symbol(s)
3           Common Shares (Par Value $1.00 Per Share)                  T
4   Depositary Shares, each representing a 1/1000t...              T PRA
5   Depositary Shares, each representing a 1/1000t...              T PRC
6   AT&T Inc. 1.875% Global Notes due December 4, ...               T 20
7   AT&T Inc. 2.650% Global Notes due December 17,...              T 21B
8      AT&T Inc. 1.450% Global Notes due June 1, 2022              T 22B
9    AT&T Inc. 2.500% Global Notes due March 15, 2023               T 23
10     AT&T Inc. 2.750% Global Notes due May 19, 2023              T 23C
11  AT&T Inc. Floating Rate Global Notes due Septe...              T 23D
12  AT&T Inc. 1.050% Global Notes due September 5,...              T 23E
13  AT&T Inc. 1.300% Global Notes due September 5,...              T 23A
14  AT&T Inc. 1.950% Global Notes due September 15...              T 23F
15   AT&T Inc. 2.400% Global Notes due March 15, 2024              T 24A
16  AT&T Inc. 3.500% Global Notes due December 17,...               T 25
17    AT&T Inc. 0.250% Global Notes due March 4, 2026              T 26E
18  AT&T Inc. 1.800% Global Notes due September 5,...              T 26D

                    4                  5                        6  \
0                 NaN                NaN                      NaN
1                 NaN                NaN    Name of each exchange
2   Trading Symbol(s)  Trading Symbol(s)      on which registered
3                   T                  T  New York Stock Exchange
4               T PRA              T PRA  New York Stock Exchange
5               T PRC              T PRC  New York Stock Exchange
6                T 20               T 20  New York Stock Exchange
7               T 21B              T 21B  New York Stock Exchange
8               T 22B              T 22B  New York Stock Exchange
9                T 23               T 23  New York Stock Exchange
10              T 23C              T 23C  New York Stock Exchange
11              T 23D              T 23D  New York Stock Exchange
12              T 23E              T 23E  New York Stock Exchange
13              T 23A              T 23A  New York Stock Exchange
14              T 23F              T 23F  New York Stock Exchange
15              T 24A              T 24A  New York Stock Exchange
16               T 25               T 25  New York Stock Exchange
17              T 26E              T 26E  New York Stock Exchange
18              T 26D              T 26D  New York Stock Exchange

                          7                        8
0                       NaN                      NaN
1     Name of each exchange    Name of each exchange
2       on which registered      on which registered
3   New York Stock Exchange  New York Stock Exchange
4   New York Stock Exchange  New York Stock Exchange
5   New York Stock Exchange  New York Stock Exchange
6   New York Stock Exchange  New York Stock Exchange
7   New York Stock Exchange  New York Stock Exchange
8   New York Stock Exchange  New York Stock Exchange
9   New York Stock Exchange  New York Stock Exchange
10  New York Stock Exchange  New York Stock Exchange
11  New York Stock Exchange  New York Stock Exchange
12  New York Stock Exchange  New York Stock Exchange
13  New York Stock Exchange  New York Stock Exchange
14  New York Stock Exchange  New York Stock Exchange
15  New York Stock Exchange  New York Stock Exchange
16  New York Stock Exchange  New York Stock Exchange
17  New York Stock Exchange  New York Stock Exchange
18  New York Stock Exchange  New York Stock Exchange
                                                    0  \
0                                                 NaN
1                                                 NaN
2                                 Title of each class
3   AT&T Inc. 2.900% Global Notes due December 4, ...
4      AT&T Inc. 1.600% Global Notes due May 19, 2028
5   AT&T Inc. 2.350% Global Notes due September 5,...
6   AT&T Inc. 4.375% Global Notes due September 14...
7   AT&T Inc. 2.600% Global Notes due December 17,...
8     AT&T Inc. 0.800% Global Notes due March 4, 2030
9      AT&T Inc. 2.050% Global Notes due May 19, 2032
10  AT&T Inc. 3.550% Global Notes due December 17,...
11  AT&T Inc. 5.200% Global Notes due November 18,...
12   AT&T Inc. 3.375% Global Notes due March 15, 2034
13   AT&T Inc. 2.450% Global Notes due March 15, 2035
14  AT&T Inc. 3.150% Global Notes due September 4,...
15     AT&T Inc. 2.600% Global Notes due May 19, 2038
16  AT&T Inc. 1.800% Global Notes due September 14...
17   AT&T Inc. 7.000% Global Notes due April 30, 2040
18     AT&T Inc. 4.250% Global Notes due June 1, 2043
19     AT&T Inc. 4.875% Global Notes due June 1, 2044
20     AT&T Inc. 4.000% Global Notes due June 1, 2049
21    AT&T Inc. 4.250% Global Notes due March 1, 2050
22  AT&T Inc. 3.750% Global Notes due September 1,...
23  AT&T Inc. 5.350% Global Notes due November 1, ...
24   AT&T Inc. 5.625% Global Notes due August 1, 2067

                                                    1  \
0                                                 NaN
1                                                 NaN
2                                 Title of each class
3   AT&T Inc. 2.900% Global Notes due December 4, ...
4      AT&T Inc. 1.600% Global Notes due May 19, 2028
5   AT&T Inc. 2.350% Global Notes due September 5,...
6   AT&T Inc. 4.375% Global Notes due September 14...
7   AT&T Inc. 2.600% Global Notes due December 17,...
8     AT&T Inc. 0.800% Global Notes due March 4, 2030
9      AT&T Inc. 2.050% Global Notes due May 19, 2032
10  AT&T Inc. 3.550% Global Notes due December 17,...
11  AT&T Inc. 5.200% Global Notes due November 18,...
12   AT&T Inc. 3.375% Global Notes due March 15, 2034
13   AT&T Inc. 2.450% Global Notes due March 15, 2035
14  AT&T Inc. 3.150% Global Notes due September 4,...
15     AT&T Inc. 2.600% Global Notes due May 19, 2038
16  AT&T Inc. 1.800% Global Notes due September 14...
17   AT&T Inc. 7.000% Global Notes due April 30, 2040
18     AT&T Inc. 4.250% Global Notes due June 1, 2043
19     AT&T Inc. 4.875% Global Notes due June 1, 2044
20     AT&T Inc. 4.000% Global Notes due June 1, 2049
21    AT&T Inc. 4.250% Global Notes due March 1, 2050
22  AT&T Inc. 3.750% Global Notes due September 1,...
23  AT&T Inc. 5.350% Global Notes due November 1, ...
24   AT&T Inc. 5.625% Global Notes due August 1, 2067

                                                    2                  3  \
0                                                 NaN                NaN
1                                                 NaN                NaN
2                                 Title of each class  Trading Symbol(s)
3   AT&T Inc. 2.900% Global Notes due December 4, ...              T 26A
4      AT&T Inc. 1.600% Global Notes due May 19, 2028              T 28C
5   AT&T Inc. 2.350% Global Notes due September 5,...              T 29D
6   AT&T Inc. 4.375% Global Notes due September 14...              T 29B
7   AT&T Inc. 2.600% Global Notes due December 17,...              T 29A
8     AT&T Inc. 0.800% Global Notes due March 4, 2030              T 30B
9      AT&T Inc. 2.050% Global Notes due May 19, 2032              T 32A
10  AT&T Inc. 3.550% Global Notes due December 17,...               T 32
11  AT&T Inc. 5.200% Global Notes due November 18,...               T 33
12   AT&T Inc. 3.375% Global Notes due March 15, 2034               T 34
13   AT&T Inc. 2.450% Global Notes due March 15, 2035               T 35
14  AT&T Inc. 3.150% Global Notes due September 4,...              T 36A
15     AT&T Inc. 2.600% Global Notes due May 19, 2038              T 38C
16  AT&T Inc. 1.800% Global Notes due September 14...              T 39B
17   AT&T Inc. 7.000% Global Notes due April 30, 2040               T 40
18     AT&T Inc. 4.250% Global Notes due June 1, 2043               T 43
19     AT&T Inc. 4.875% Global Notes due June 1, 2044               T 44
20     AT&T Inc. 4.000% Global Notes due June 1, 2049              T 49A
21    AT&T Inc. 4.250% Global Notes due March 1, 2050               T 50
22  AT&T Inc. 3.750% Global Notes due September 1,...              T 50A
23  AT&T Inc. 5.350% Global Notes due November 1, ...                TBB
24   AT&T Inc. 5.625% Global Notes due August 1, 2067                TBC

                    4                  5                        6  \
0                 NaN                NaN                      NaN
1                 NaN                NaN    Name of each exchange
2   Trading Symbol(s)  Trading Symbol(s)      on which registered
3               T 26A              T 26A  New York Stock Exchange
4               T 28C              T 28C  New York Stock Exchange
5               T 29D              T 29D  New York Stock Exchange
6               T 29B              T 29B  New York Stock Exchange
7               T 29A              T 29A  New York Stock Exchange
8               T 30B              T 30B  New York Stock Exchange
9               T 32A              T 32A  New York Stock Exchange
10               T 32               T 32  New York Stock Exchange
11               T 33               T 33  New York Stock Exchange
12               T 34               T 34  New York Stock Exchange
13               T 35               T 35  New York Stock Exchange
14              T 36A              T 36A  New York Stock Exchange
15              T 38C              T 38C  New York Stock Exchange
16              T 39B              T 39B  New York Stock Exchange
17               T 40               T 40  New York Stock Exchange
18               T 43               T 43  New York Stock Exchange
19               T 44               T 44  New York Stock Exchange
20              T 49A              T 49A  New York Stock Exchange
21               T 50               T 50  New York Stock Exchange
22              T 50A              T 50A  New York Stock Exchange
23                TBB                TBB  New York Stock Exchange
24                TBC                TBC  New York Stock Exchange

                          7                        8
0                       NaN                      NaN
1     Name of each exchange    Name of each exchange
2       on which registered      on which registered
3   New York Stock Exchange  New York Stock Exchange
4   New York Stock Exchange  New York Stock Exchange
5   New York Stock Exchange  New York Stock Exchange
6   New York Stock Exchange  New York Stock Exchange
7   New York Stock Exchange  New York Stock Exchange
8   New York Stock Exchange  New York Stock Exchange
9   New York Stock Exchange  New York Stock Exchange
10  New York Stock Exchange  New York Stock Exchange
11  New York Stock Exchange  New York Stock Exchange
12  New York Stock Exchange  New York Stock Exchange
13  New York Stock Exchange  New York Stock Exchange
14  New York Stock Exchange  New York Stock Exchange
15  New York Stock Exchange  New York Stock Exchange
16  New York Stock Exchange  New York Stock Exchange
17  New York Stock Exchange  New York Stock Exchange
18  New York Stock Exchange  New York Stock Exchange
19  New York Stock Exchange  New York Stock Exchange
20  New York Stock Exchange  New York Stock Exchange
21  New York Stock Exchange  New York Stock Exchange
22  New York Stock Exchange  New York Stock Exchange
23  New York Stock Exchange  New York Stock Exchange
24  New York Stock Exchange  New York Stock Exchange
                        0                        1                        2   \
0                      NaN                      NaN                      NaN
1  Large Accelerated Filer  Large Accelerated Filer  Large Accelerated Filer
2    Non-accelerated filer    Non-accelerated filer    Non-accelerated filer
3                      NaN                      NaN                      NaN

    3    4    5                          6                          7   \
0  NaN  NaN  NaN                        NaN                        NaN
1    ☒    ☒    ☒          Accelerated Filer          Accelerated Filer
2    ☐    ☐    ☐  Smaller reporting company  Smaller reporting company
3  NaN  NaN  NaN    Emerging growth company    Emerging growth company

                          8    9    10   11
0                        NaN  NaN  NaN  NaN
1          Accelerated Filer    ☐    ☐    ☐
2  Smaller reporting company    ☐    ☐    ☐
3    Emerging growth company    ☐    ☐    ☐
                                                   0   \
0                                                 NaN
1                                           AT&T INC.
2                   CONSOLIDATED STATEMENTS OF INCOME
3        Dollars in millions except per share amounts
4                                         (Unaudited)
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                  Operating Revenues
9                                             Service
10                                          Equipment
11                           Total operating revenues
12                                                NaN
13                                 Operating Expenses
14                                   Cost of revenues
15                                          Equipment
16              Broadcast, programming and operations
17  Other cost of revenues (exclusive of depreciat...
18                Selling, general and administrative
19                 Asset impairments and abandonments
20                      Depreciation and amortization
21                           Total operating expenses
22                                   Operating Income
23                             Other Income (Expense)
24                                   Interest expense
25          Equity in net income (loss) of affiliates
26                       Other income (expense) — net
27                       Total other income (expense)
28                         Income Before Income Taxes
29                                 Income tax expense
30                                         Net Income
31  Less: Net Income Attributable to Noncontrollin...
32                    Net Income Attributable to AT&T
33                    Less: Preferred Stock Dividends
34            Net Income Attributable to Common Stock
35  Basic Earnings Per Share Attributable toCommon...
36  Diluted Earnings Per Share Attributable toComm...
37  Weighted Average Number of Common SharesOutsta...
38  Weighted Average Number of Common SharesOutsta...

                                                   1   \
0                                                 NaN
1                                           AT&T INC.
2                   CONSOLIDATED STATEMENTS OF INCOME
3        Dollars in millions except per share amounts
4                                         (Unaudited)
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                  Operating Revenues
9                                             Service
10                                          Equipment
11                           Total operating revenues
12                                                NaN
13                                 Operating Expenses
14                                   Cost of revenues
15                                          Equipment
16              Broadcast, programming and operations
17  Other cost of revenues (exclusive of depreciat...
18                Selling, general and administrative
19                 Asset impairments and abandonments
20                      Depreciation and amortization
21                           Total operating expenses
22                                   Operating Income
23                             Other Income (Expense)
24                                   Interest expense
25          Equity in net income (loss) of affiliates
26                       Other income (expense) — net
27                       Total other income (expense)

In [124]:
df[6].iloc[3:,[0,16,22]]

,0,16,22
3,Dollars in millions,NaN,NaN
4,(Unaudited),NaN,NaN
5,NaN,Nine months ended,Nine months ended
6,NaN,"September 30,","September 30,"
7,NaN,2020,2019
8,Net income,9694,12271
9,"Other comprehensive income (loss), net of tax:",NaN,NaN
10,Foreign currency:,NaN,NaN
11,"Translation adjustment (includes $(2), $(17), ...","(1,459)",(181)
12,Securities:,NaN,NaN
13,"Net unrealized gains (losses), net of taxes of...",81,67
14,Derivative instruments:,NaN,NaN
15,"Net unrealized gains (losses), net of taxes of...","(2,166)","(1,006)"
16,Reclassification adjustment included in net in...,44,24
17,Defined benefit postretirement plans:,NaN,NaN
18,Amortization of net prior service credit inclu...,"(1,382)","(1,031)"
19,Other comprehensive income (loss),"(4,882)","(2,127)"
20,Total comprehensive income,4812,10144
21,Less: Total comprehensive income attributable ...,(926),(747)
22,Total Comprehensive Income Attributable to AT&T,3886,9397

In [129]:
df[7].iloc[:,[0,4,10]]

,0,4,10
0,NaN,NaN,NaN
1,AT&T INC.,AT&T INC.,AT&T INC.
2,CONSOLIDATED BALANCE SHEETS,CONSOLIDATED BALANCE SHEETS,CONSOLIDATED BALANCE SHEETS
3,Dollars in millions except per share amounts,Dollars in millions except per share amounts,Dollars in millions except per share amounts
4,NaN,"September 30, 2020","December 31, 2019"
5,Assets,(Unaudited),NaN
6,Current Assets,NaN,NaN
7,Cash and cash equivalents,9758,12130
8,Accounts receivable — net of related allowance...,19379,22636
9,Prepaid expenses,1420,1631
10,Other current assets,19414,18364
11,Total current assets,49971,54761
12,Noncurrent Inventories and Theatrical Film and...,13948,12434
13,"Property, plant and equipment",333797,333538
14,Less: accumulated depreciation and amortization,"(205,075)","(203,410)"
15,"Property, Plant and Equipment — Net",128722,130128
16,Goodwill,143688,146241
17,Licenses — Net,98397,97907
18,Trademarks and Trade Names — Net,23575,23567
19,Distribution Networks — Net,14249,15345
20,Other Intangible Assets — Net,17523,20798
21,Investments in and Advances to Equity Affiliates,2325,3695
22,Operating Lease Right-Of-Use Assets,24546,24039
23,Other Assets,21609,22754
24,Total Assets,538553,551669
25,Liabilities and Stockholders’ Equity,NaN,NaN
26,Current Liabilities,NaN,NaN
27,Debt maturing within one year,5898,11838
28,Accounts payable and accrued liabilities,42728,45956
29,Advanced billings and customer deposits,5862,6124
30,Accrued taxes,1336,1212
31,Dividends payable,3741,3781
32,Total current liabilities,59565,68911
33,Long-Term Debt,152980,151309
34,Deferred Credits and Other Noncurrent Liabilities,NaN,NaN
35,Deferred income taxes,60448,59502
36,Postemployment benefit obligation,17928,18788
37,Operating lease liabilities,22056,21804
38,Other noncurrent liabilities,30520,29421
39,Total deferred credits and other noncurrent li...,130952,129515
40,Stockholders’ Equity,NaN,NaN
41,"Preferred stock ($1 par value, 10,000,000 auth...",NaN,NaN
42,"Series A (48,000 issued and outstanding at Sep...",—,—
43,"Series B (20,000 issued and outstanding at Sep...",—,—
44,"Series C (70,000 issued and outstanding at Sep...",—,—
45,"Common stock ($1 par value, 14,000,000,000 aut...",7621,7621
46,Additional paid-in capital,130139,126279
47,Retained earnings,55094,57936
48,"Treasury stock (495,703,331 at September 30, 2...","(17,950)","(13,085)"
49,Accumulated other comprehensive income,649,5470
50,Noncontrolling interest,19503,17713
51,Total stockholders’ equity,195056,201934
52,Total Liabilities and Stockholders’ Equity,538553,551669

In [130]:
len(df)

71

In [131]:
df[16]

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019",...,"For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019","For the nine months ended September 30, 2019"
2,NaN,NaN,NaN,Revenues,Revenues,Revenues,NaN,NaN,NaN,Operations and Support Expenses,...,NaN,Equity in NetIncome (Loss) ofAffiliates,Equity in NetIncome (Loss) ofAffiliates,Equity in NetIncome (Loss) ofAffiliates,NaN,NaN,NaN,Segment Contribution,Segment Contribution,Segment Contribution
3,Communications,Communications,Communications,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mobility,Mobility,Mobility,$,52356,NaN,NaN,NaN,NaN,$,...,NaN,$,—,NaN,NaN,NaN,NaN,$,16818,NaN
5,Entertainment Group,Entertainment Group,Entertainment Group,33893,33893,NaN,NaN,NaN,NaN,25839,...,NaN,—,—,NaN,NaN,NaN,NaN,4076,4076,NaN
6,Business Wireline,Business Wireline,Business Wireline,19588,19588,NaN,NaN,NaN,NaN,12029,...,NaN,—,—,NaN,NaN,NaN,NaN,3824,3824,NaN
7,Total Communications,Total Communications,Total Communications,105837,105837,NaN,NaN,NaN,NaN,67379,...,NaN,—,—,NaN,NaN,NaN,NaN,24718,24718,NaN
8,WarnerMedia,WarnerMedia,WarnerMedia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Turner,Turner,Turner,9860,9860,NaN,NaN,NaN,NaN,5813,...,NaN,46,46,NaN,NaN,NaN,NaN,3926,3926,NaN
10,Home Box Office,Home Box Office,Home Box Office,5045,5045,NaN,NaN,NaN,NaN,3124,...,NaN,40,40,NaN,NaN,NaN,NaN,1894,1894,NaN
11,Warner Bros.,Warner Bros.,Warner Bros.,10240,10240,NaN,NaN,NaN,NaN,8543,...,NaN,(19),(19),NaN,NaN,NaN,NaN,1556,1556,NaN
12,Eliminations and other,Eliminations and other,Eliminations and other,845,845,NaN,NaN,NaN,NaN,438,...,NaN,70,70,NaN,NaN,NaN,NaN,408,408,NaN
13,Total WarnerMedia,Total WarnerMedia,Total WarnerMedia,25990,25990,NaN,NaN,NaN,NaN,17918,...,NaN,137,137,NaN,NaN,NaN,NaN,7784,7784,NaN
14,Latin America,Latin America,Latin America,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Vrio,Vrio,Vrio,3112,3112,NaN,NaN,NaN,NaN,2598,...,NaN,25,25,NaN,NaN,NaN,NaN,43,43,NaN
16,Mexico,Mexico,Mexico,2093,2093,NaN,NaN,NaN,NaN,2312,...,NaN,—,—,NaN,NaN,NaN,NaN,(591),(591),NaN
17,Total Latin America,Total Latin America,Total Latin America,5205,5205,NaN,NaN,NaN,NaN,4910,...,NaN,25,25,NaN,NaN,NaN,NaN,(548),(548),NaN
18,Segment Total,Segment Total,Segment Total,137032,137032,NaN,NaN,NaN,NaN,90207,...,NaN,$,162,NaN,NaN,NaN,NaN,$,31954,NaN
19,Corporate and Other,Corporate and Other,Corporate and Other,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Corporate,Corporate,Corporate,1290,1290,NaN,NaN,NaN,NaN,2129,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Acquisition-relateditems,Acquisition-relateditems,Acquisition-relateditems,(72),(72),NaN,NaN,NaN,NaN,579,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Certain significantitems,Certain significantitems,Certain significantitems,—,—,NaN,NaN,NaN,NaN,381,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Eliminations andconsolidations,Eliminations andconsolidations,Eliminations andconsolidations,"(3,878)","(3,878)",NaN,NaN,NaN,NaN,"(2,814)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,AT&T Inc.,AT&T Inc.,AT&T Inc.,$,134372,NaN,NaN,NaN,NaN,$,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [128]:
Balance_Sheet.iloc[1:,[1,3,10]]

,1,3,10
1,AT&T INC.,AT&T INC.,AT&T INC.
2,CONSOLIDATED STATEMENTS OF CHANGES IN STOCKHOL...,CONSOLIDATED STATEMENTS OF CHANGES IN STOCKHOL...,CONSOLIDATED STATEMENTS OF CHANGES IN STOCKHOL...
3,Dollars and shares in millions except per shar...,Dollars and shares in millions except per shar...,Dollars and shares in millions except per shar...
4,(Unaudited),(Unaudited),(Unaudited)
5,NaN,Three months ended,Three months ended
6,NaN,"September 30, 2020","September 30, 2020"
7,NaN,Shares,Amount
8,Preferred Stock - Series A,NaN,NaN
9,Balance at beginning of period,—,—
10,Issuance of stock,—,—
11,Balance at end of period,—,—
12,Preferred Stock - Series B,NaN,NaN
13,Balance at beginning of period,—,—
14,Issuance of stock,—,—
15,Balance at end of period,—,—
16,Preferred Stock - Series C,NaN,NaN
17,Balance at beginning of period,—,—
18,Issuance of stock,—,—
19,Balance at end of period,—,—
20,Common Stock,NaN,NaN
21,Balance at beginning of period,7621,7621
22,Issuance of stock,—,—
23,Balance at end of period,7621,7621
24,Additional Paid-In Capital,NaN,NaN
25,Balance at beginning of period,NaN,130046
26,Repurchase and acquisition ofcommon stock,NaN,—
27,Issuance of preferred stock,NaN,—
28,Issuance of treasury stock,NaN,(2)
29,Share-based payments,NaN,91
30,Changes related to acquisition ofinterests hel...,NaN,4
31,Balance at end of period,NaN,130139
32,Retained Earnings,NaN,NaN
33,Balance at beginning of period,NaN,56045
34,Cumulative effect of accountingchange and othe...,NaN,—
35,Adjusted beginning balance,NaN,56045
36,Net income attributable to AT&T,NaN,2816
37,Preferred stock dividends,NaN,(35)
38,"Common stock dividends ( $0.52,$0.51, $1.56, a...",NaN,"(3,732)"
39,Balance at end of period,NaN,55094

In [64]:
# Balance_Sheet.iloc[2:,[0,2,6]]
Balance_Sheet.iloc[2:,[0,3,9]]

                                                    0        3            9
2                                                 NaN      NaN  (unaudited)
3                                              Assets      NaN          NaN
4                                     Current assets:      NaN          NaN
5                           Cash and cash equivalents        $            $
6                               Marketable securities   101177        97585
7   Total cash, cash equivalents, and marketable s...   119675       117229
8                            Accounts receivable, net    25326        21825
9                        Income taxes receivable, net     2166         1910
10                                          Inventory      999          889
11                               Other current assets     4412         5165
12                               Total current assets   152578       147018
13                         Non-marketable investments    13078        12367
14                              Deferred income taxes      721          730
15                        Property and equipment, net    73646        76747
16                             Operating lease assets    10941        11219
17                             Intangible assets, net     1979         1840
18                                           Goodwill    20624        20734
19                           Other non-current assets     2342         2748
20                                       Total assets        $            $
21               Liabilities and Stockholders’ Equity      NaN          NaN
22                               Current liabilities:      NaN          NaN
23                                   Accounts payable        $            $
24                                                NaN      NaN          NaN
25                  Accrued compensation and benefits     8495         5656
26     Accrued expenses and other current liabilities    23067        22601
27                              Accrued revenue share     5916         4982
28                                   Deferred revenue     1908         1938
29                          Income taxes payable, net      274          913
30                          Total current liabilities    45221        40189
31                                     Long-term debt     4554         5016
32                      Deferred revenue, non-current      358          350
33                  Income taxes payable, non-current     9885         9207
34                              Deferred income taxes     1701         2079
35                        Operating lease liabilities    10214        10476
36                        Other long-term liabilities     2534         2427
37                                  Total liabilities    74467        69744
38            Commitments and Contingencies (Note 10)      NaN          NaN
39                              Stockholders’ equity:      NaN          NaN
40  Convertible preferred stock, $0.001 par value ...        0            0
41  Class A and Class B common stock, and Class C ...    50552        53688
42               Accumulated other comprehensive loss  (1,232)      (1,097)
43                                  Retained earnings   152122       151068
44                         Total stockholders’ equity   201442       203659
45         Total liabilities and stockholders’ equity        $            $

In [42]:
df

,Seq,Description,Document,Type,Size
0,1.0,10-Q,goog-20200331.htm iXBRL,10-Q,2798365
1,2.0,EX-31.01,googexhibit3101q12020.htm,EX-31.01,12318
2,3.0,EX-31.02,googexhibit3102q12020.htm,EX-31.02,12366
3,4.0,EX-32.01,googexhibit3201q12020.htm,EX-32.01,11172
4,NaN,Complete submission text file,0001652044-20-000021.txt,NaN,12641678

In [90]:
# 뉴스기사
import requests

stock = 'T'
key = 'ebdb805e90e347c37cd716161d993989'
# 'income-statement'
# url = f'https://financialmodelingprep.com/api/v3/{fn}/{stock}?apikey={key}'
url = f'https://financialmodelingprep.com/api/v3/stock_news?tickers={stock}&limit=50&apikey={key}'


news = requests.get(url).json()
news

In [ ]:
# https://financialmodelingprep.com/api/v3/etf-holder/SPY?apikey=ebdb805e90e347c37cd716161d993989
# https://financialmodelingprep.com/api/v3/stock_news?tickers=T&limit=50&apikey=ebdb805e90e347c37cd716161d993989